#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    echo "Please provide ShooterGameServer.exe arguments:"
    echo "    Example: Ocean?ServerX=0?ServerY=0?MaxPlayers=10?ReservedPlayerSlots=5?QueryPort=57555?Port=5755?SeamlessIP=XX_YOUR_PUB_IP_XX -NoBattlEye -log -server"
    echo ""
    exit 1
fi

export DISPLAY=:20
Xvfb :20 -screen 0 1366x768x16 &
sleep 1
wine /atlas/ShooterGame/Binaries/Win64/ShooterGameServer.exe "$@"
